[package]
name = "pgmorph"
version = "0.1.0"
edition = "2024"

[lib]
name = "pgmorph"
path = "src/lib.rs"

[[bin]]
name = "pgmorph"
path = "src/main.rs"

[dependencies]
clap = { version = "4.6.1", features = ["derive", "env"] }
tokio = { version = "1.52.3", features = ["full"] }
tokio-postgres = "0.7.17"
log = "0.4.32"

[dev-dependencies]
testcontainers = "0.27.3"
testcontainers-modules = {version = "0.15.0", features = ["postgres"]}
